[package]
name = "store"
version.workspace = true
edition.workspace = true

[dependencies]
sqlx = { version = "0.7.4", features = ["sqlite", "runtime-tokio-rustls"] }

chrono = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

types = { path = "../types" }
