printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: consistent
jsxSingleQuote: true
trailingComma: all
bracketSpacing: true
bracketSameLine: false
arrowParens: avoid
overrides:
  - files: '*.{ts,tsx}'
    options:
      parser: typescript
  - files: '*.{js,jsx}'
    options:
      parser: meriyah
  - files: '*.json'
    options:
      parser: json
  - files: '*.css'
    options:
      parser: css
  - files: '*.html'
    options:
      parser: html
  - files: '*.{yaml,yml}'
    options:
      parser: yaml
  - files: '*.md'
    options:
      parser: markdown
