[package]
name = "ws"
version.workspace = true
edition.workspace = true

[dependencies]
rand = "0.8.5"
rmp-serde = "1.3.0"
serde_json = "1.0.117"

axum = { workspace = true }
hyper = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
