name: Check

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - v*

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  server:
    name: Check Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2
      - name: Format
        run: cargo fmt --all -- --check
      - name: Install cargo-hack
        run: cargo install cargo-hack
      - name: Check main
        run: cargo hack --feature-powerset check --verbose --workspace
      - name: Check tests
        run: cargo hack --feature-powerset check --verbose --workspace --tests
      - name: Check examples
        run: cargo hack --feature-powerset check --verbose --workspace --examples
      - name: Lint main
        run: cargo hack --feature-powerset clippy --verbose --workspace -- -W clippy::pedantic
      - name: Lint tests
        run: cargo hack --feature-powerset clippy --verbose --workspace --tests -- -W clippy::pedantic
      - name: Lint examples
        run: cargo hack --feature-powerset clippy --verbose --workspace --examples -- -W clippy::pedantic
      - name: Test
        run: cargo hack --feature-powerset test --verbose --workspace --no-fail-fast
  wasm:
    name: Check Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: yarn
      - name: Format
        run: yarn lint:prettier
      - name: Lint
        run: yarn lint:eslint
      - name: Test
        run: echo 'YOLO!!'
